src/HelloAspNetCore/Models/Layout.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HelloAspNetCore.Models.Pages;

namespace HelloAspNetCore.Models
{
    public class Layout
    {
        public List<LocationPair> Routes { get; set; }
        public Layout()
        {
            Routes = new List<LocationPair>();
        }

    }

}

src/HelloAspNetCore/Models/Location.cs
using HelloAspNetCore.Services.HSL;

namespace HelloAspNetCore.Models
{
    public class Location
    {
        public int LocationId { get; set; }
        public string FriendlyName { get; set; }

    }
}

src/HelloAspNetCore/Models/LocationPair.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HelloAspNetCore.Models
{
    public class LocationPair
    {
        public Location From { get; set; }
        public Location To { get; set; }
    }
}

src/HelloAspNetCore/Models/Pages/HomePage.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HelloAspNetCore.Models.Pages
{
    public class HomePage: IPage
    {
        public Layout Layout { get; set; }
    }
}

src/HelloAspNetCore/Models/Pages/IPage.cs
using System.Security.Cryptography.X509Certificates;

namespace HelloAspNetCore.Models.Pages
{
    public interface IPage
    {
        Layout Layout { get; set; }
    }
}

src/HelloAspNetCore/Models/Pages/RouteResultPage.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HelloAspNetCore.JsonClasses;

namespace HelloAspNetCore.Models.Pages
{
    public class RouteResultPage: IPage
    {
        public Layout Layout { get; set; }
        public List<HSLRoute> Routes {get; set;}

        public RouteResultPage()
        {
            Routes = new List<HSLRoute>();
        }
    }
}

src/HelloAspNetCore/Controllers/HomeController.cs
using System.Threading.Tasks;
using HelloAspNetCore.Models.Pages;
using HelloAspNetCore.Services;
using HelloAspNetCore.Services.HSL;
using Microsoft.AspNet.Mvc;

namespace HelloAspNetCore.Controllers
{
    public class HomeController : Controller
    {
        private readonly IHslRouteSolver _hslRouteSolver;
        private readonly ILayoutFactory _layoutFactory;

        public HomeController(IHslRouteSolver hslRouteSolver, ILayoutFactory layoutFactory)
        {
            _hslRouteSolver = hslRouteSolver;
            _layoutFactory = layoutFactory;
        }

        public IActionResult Index()
        {
            var homePage = new HomePage();
            homePage.Layout = _layoutFactory.Create();

            return View("~/Views/Pages/Home.cshtml", homePage);
        }
    }
}

src/HelloAspNetCore/Controllers/RouteResultController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HelloAspNetCore.Models.Pages;
using HelloAspNetCore.Services;
using HelloAspNetCore.Services.HSL;
using Microsoft.AspNet.Mvc;


namespace HelloAspNetCore.Controllers
{
    [Route("HaeReitti")]
    public class RouteResultController : Controller
    {

        private readonly IHslRouteSolver _hslRouteSolver;
        private readonly ILayoutFactory _layoutFactory;

        public RouteResultController(IHslRouteSolver hslRouteSolver, ILayoutFactory layoutFactory)
        {
            _hslRouteSolver = hslRouteSolver;
            _layoutFactory = layoutFactory;
        }

        public async Task<IActionResult> Index(LocationEnum from, LocationEnum to)
        {
            var routes = _hslRouteSolver.GetRoute(from, to);
            var resultPage = new RouteResultPage
            {
                Layout = _layoutFactory.Create()
            };

            resultPage.Routes = await routes;
            return View("~/Views/Pages/RouteResult.cshtml", resultPage);
        }
    }
}

src/HelloAspNetCore/Views/Home/Index.cshtml
<div class="container">

    <!-- Main component for a primary marketing message or call to action -->
    <div class="jumbotron">
        <h1>HSL Reitin etsijä</h1>
        <p>Klikkaileppa itsellesi hieman reittejä</p>
    </div>

</div> <!-- /container -->

src/HelloAspNetCore/Views/Shared/_Layout.cshtml
@model HelloAspNetCore.Models.Pages.IPage

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>@ViewData["Title"] - FullASPNetCoreExample</title>
        <environment names="Development">
            <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
            <link rel="stylesheet" href="~/css/site.css" />
        </environment>
        <environment names="Staging,Production">
            <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.5/css/bootstrap.min.css"
                  asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
                  asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
            <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        </environment>
    </head>
<body>
    <!-- Static navbar -->
    <div class="navbar navbar-default navbar-static-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <span class="navbar-brand">;-)</span>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="/">Home</a></li>
                    @foreach (var locationPair in @Model.Layout.Routes)
                    {
                        <li>
                            @*@Html.ActionLink("Reitti with HTMLhelper", "Index", "HslRoute", new {from = @locationPair.From.LocationId, to = @locationPair.To.LocationId})*@
                            <a asp-controller="RouteResult" asp-action="Index" asp-route-from="@locationPair.From.LocationId" asp-route-to="@locationPair.To.LocationId">@locationPair.From.FriendlyName -> @locationPair.To.FriendlyName</a>
                        </li>
                    }

                </ul>
            </div><!--/.nav-collapse -->
        </div>
    </div>

@RenderBody()
</body>
</html>